/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as ApiSplatRouteImport } from "./routes/api.$"
import { Route as IndexRouteImport } from "./routes/index"

const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
	id: "/about",
	path: "/about",
	getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
	id: "/api/$",
	path: "/api/$",
	getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute
	"/about": typeof AboutRoute
	"/api/$": typeof ApiSplatRoute
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute
	"/about": typeof AboutRoute
	"/api/$": typeof ApiSplatRoute
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport
	"/": typeof IndexRoute
	"/about": typeof AboutRoute
	"/api/$": typeof ApiSplatRoute
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath
	fullPaths: "/" | "/about" | "/api/$"
	fileRoutesByTo: FileRoutesByTo
	to: "/" | "/about" | "/api/$"
	id: "__root__" | "/" | "/about" | "/api/$"
	fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute
	AboutRoute: typeof AboutRoute
	ApiSplatRoute: typeof ApiSplatRoute
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/"
			path: "/"
			fullPath: "/"
			preLoaderRoute: typeof IndexRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/about": {
			id: "/about"
			path: "/about"
			fullPath: "/about"
			preLoaderRoute: typeof AboutRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/api/$": {
			id: "/api/$"
			path: "/api/$"
			fullPath: "/api/$"
			preLoaderRoute: typeof ApiSplatRouteImport
			parentRoute: typeof rootRouteImport
		}
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	AboutRoute: AboutRoute,
	ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { startInstance } from "./start.ts"

declare module "@tanstack/react-start" {
	interface Register {
		ssr: true
		router: Awaited<ReturnType<typeof getRouter>>
		config: Awaited<ReturnType<typeof startInstance.getOptions>>
	}
}
